######################################################################
# Automatically generated by qmake (2.01a) Tue May 19 19:51:24 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MyGraph.h MyGraph.cpp
SOURCES += main.cpp MyGraph.cpp
